# This is specific to my environment, modify it as needed.

version: '3.7'
services:
  app:
    image: nginx
    restart: always
    volumes:
      - ./build:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.app.port=80"
      - "traefik.app.backend=app"
      - "traefik.app.frontend.rule=Host:live.uprootx.com"   
      - "traefik.app.frontend.entryPoints=http,https"
      - "traefik.docker.network=net" 
    networks:
      - traefik_proxy
  restreamer:
    image: datarhei/restreamer:latest
    restart: always
    environment: 
      - RS_USERNAME=${RS_USERNAME}
      - RS_PASSWORD=${RS_PASSWORD}
      - RS_TOKEN=${RS_TOKEN}
    networks: 
      - traefik_proxy
    ports:
      - '1935:1935'
      - "8111:8080"
    volumes:
      - restreamerdb:/restreamer/db
    labels:
      - "traefik.enable=true"
      - "traefik.restreamer.port=8080"
      - "traefik.restreamer.backend=restreamer"
      - "traefik.restreamer.frontend.rule=Host:restreamer.uprootx.com"   
      - "traefik.restreamer.frontend.entryPoints=http,https"
      - "traefik.docker.network=net" 
  traefik:
    container_name: traefik
    restart: unless-stopped
    image: traefik:v1.7
    command:
        --configFile=/var/traefik/traefik.toml
    ports:
      - "445:443"
      - "82:80"
    networks:
      - net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/var/traefik/traefik.toml:ro
      - traefik-log:/log
      - traefik-certs:/etc/traefik/acme    
    labels:
      - "traefik.enable=false"            
volumes:
  restreamerdb:
  traefik-log:
  traefik-certs:
networks:
  net:
  traefik_proxy:
